const watchlistData = [{
	"Title": "The Dig",
	"Year": "2021",
	"Rated": "PG-13",
	"Released": "29 Jan 2021",
	"Runtime": "112 min",
	"Genre": "Biography, Drama, History",
	"Director": "Simon Stone",
	"imdbRating": "7.1",
	"imdbID": "tt3661210",
	"Type": "movie",
	"DateCompleted": "2/6/21"
},
{
	"Title": "The Breadwinner",
	"Year": "2017",
	"Rated": "PG-13",
	"Released": "17 Nov 2017",
	"Runtime": "94 min",
	"Genre": "Animation, Drama, Family",
	"Director": "Nora Twomey",
	"imdbRating": "7.7",
	"imdbID": "tt3901826",
	"Type": "movie",
	"DateCompleted": "2/6/21"
},
{
	"Title": "Okko's Inn",
	"Year": "2018",
	"Rated": "PG",
	"Released": "21 Sep 2018",
	"Runtime": "94 min",
	"Genre": "Animation, Adventure, Drama",
	"Director": "Kitarô Kôsaka",
	"imdbRating": "7.0",
	"imdbID": "tt8328740",
	"Type": "movie",
	"DateCompleted": "2/13/21"
}, {
	"Title": "Spycraft",
	"Year": "2020–2022",
	"Rated": "TV-MA",
	"Released": "20 Jan 2021",
	"Runtime": "271 min",
	"Genre": "Documentary",
	"Director": "N/A",
	"imdbRating": "6.7",
	"imdbID": "tt13789092",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "2/16/21",
	"seasonsWatched": "1"
}, {
	"Title": "Ozark",
	"Year": "2017–2022",
	"Rated": "TV-MA",
	"Released": "21 Jul 2017",
	"Runtime": "60 min",
	"Genre": "Crime, Drama, Thriller",
	"Director": "N/A",
	"imdbRating": "8.5",
	"imdbID": "tt5071412",
	"Type": "series",
	"totalSeasons": "4",
	"DateCompleted": "2/19/21",
	"seasonsWatched": "3"
}, {
	"Title": "Atomic Blonde",
	"Year": "2017",
	"Rated": "R",
	"Released": "28 Jul 2017",
	"Runtime": "115 min",
	"Genre": "Action, Thriller",
	"Director": "David Leitch",
	"imdbRating": "6.7",
	"imdbID": "tt2406566",
	"Type": "movie",
	"DateCompleted": "2/22/21"
}, {
	"Title": "Prometheus",
	"Year": "2012",
	"Rated": "R",
	"Released": "08 Jun 2012",
	"Runtime": "124 min",
	"Genre": "Adventure, Mystery, Sci-Fi",
	"Director": "Ridley Scott",
	"imdbRating": "7.0",
	"imdbID": "tt1446714",
	"Type": "movie",
	"DateCompleted": "2/23/21"
}, {
	"Title": "Giri/Haji",
	"Year": "2019",
	"Rated": "TV-MA",
	"Released": "10 Jan 2020",
	"Runtime": "461 min",
	"Genre": "Crime, Drama, Mystery",
	"Director": "N/A",
	"imdbRating": "7.8",
	"imdbID": "tt8001106",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "2/27/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Hobbit: An Unexpected Journey *",
	"Year": "2012",
	"Rated": "PG-13",
	"Released": "14 Dec 2012",
	"Runtime": "169 min",
	"Genre": "Adventure, Fantasy",
	"Director": "Peter Jackson",
	"imdbRating": "7.8",
	"imdbID": "tt0903624",
	"Type": "movie",
	"DateCompleted": "2/28/21"
}, {
	"Title": "Mission: Impossible - Fallout",
	"Year": "2018",
	"Rated": "PG-13",
	"Released": "27 Jul 2018",
	"Runtime": "147 min",
	"Genre": "Action, Adventure, Thriller",
	"Director": "Christopher McQuarrie",
	"imdbRating": "7.7",
	"imdbID": "tt4912910",
	"Type": "movie",
	"DateCompleted": "3/4/21"
}, {
	"Title": "WandaVision",
	"Year": "2021",
	"Rated": "TV-PG",
	"Released": "15 Jan 2021",
	"Runtime": "350 min",
	"Genre": "Action, Comedy, Drama",
	"Director": "N/A",
	"imdbRating": "8.0",
	"imdbID": "tt9140560",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "3/5/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Hobbit: The Desolation of Smaug *",
	"Year": "2013",
	"Rated": "PG-13",
	"Released": "13 Dec 2013",
	"Runtime": "161 min",
	"Genre": "Adventure, Fantasy",
	"Director": "Peter Jackson",
	"imdbRating": "7.8",
	"imdbID": "tt1170358",
	"Type": "movie",
	"DateCompleted": "3/6/21"
}, {
	"Title": "The Hobbit: The Battle of the Five Armies",
	"Year": "2014",
	"Rated": "PG-13",
	"Released": "17 Dec 2014",
	"Runtime": "144 min",
	"Genre": "Adventure, Fantasy",
	"Director": "Peter Jackson",
	"imdbRating": "7.4",
	"imdbID": "tt2310332",
	"Type": "movie",
	"DateCompleted": "3/6/21"
}, {
	"Title": "The Lord of the Rings: The Fellowship of the Ring *",
	"Year": "2001",
	"Rated": "PG-13",
	"Released": "19 Dec 2001",
	"Runtime": "178 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "Peter Jackson",
	"imdbRating": "8.8",
	"imdbID": "tt0120737",
	"Type": "movie",
	"DateCompleted": "3/7/21"
}, {
	"Title": "The Lord of the Rings: The Two Towers *",
	"Year": "2002",
	"Rated": "PG",
	"Released": "18 Dec 2002",
	"Runtime": "179 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "Peter Jackson",
	"imdbRating": "8.7",
	"imdbID": "tt0167261",
	"Type": "movie",
	"DateCompleted": "3/7/21"
}, {
	"Title": "The Lord of the Rings: The Return of the King *",
	"Year": "2003",
	"Rated": "PG-13",
	"Released": "17 Dec 2003",
	"Runtime": "201 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "Peter Jackson",
	"imdbRating": "8.9",
	"imdbID": "tt0167260",
	"Type": "movie",
	"DateCompleted": "3/7/21"
}, {
	"Title": "Mercury 13",
	"Year": "2018",
	"Rated": "TV-PG",
	"Released": "20 Apr 2018",
	"Runtime": "78 min",
	"Genre": "Documentary",
	"Director": "David Sington Heather Walsh",
	"imdbRating": "6.9",
	"imdbID": "tt8139850",
	"Type": "movie",
	"DateCompleted": "3/12/21"
}, {
	"Title": "Maleficent",
	"Year": "2014",
	"Rated": "PG",
	"Released": "30 May 2014",
	"Runtime": "97 min",
	"Genre": "Adventure, Family, Fantasy",
	"Director": "Robert Stromberg",
	"imdbRating": "7.0",
	"imdbID": "tt1587310",
	"Type": "movie",
	"DateCompleted": "3/20/21"
}, {
	"Title": "Maleficent: Mistress of Evil",
	"Year": "2019",
	"Rated": "PG",
	"Released": "18 Oct 2019",
	"Runtime": "119 min",
	"Genre": "Adventure, Family, Fantasy",
	"Director": "Joachim Rønning",
	"imdbRating": "6.6",
	"imdbID": "tt4777008",
	"Type": "movie",
	"DateCompleted": "3/21/21"
}, {
	"Title": "Miss Peregrine's Home for Peculiar Children",
	"Year": "2016",
	"Rated": "PG-13",
	"Released": "30 Sep 2016",
	"Runtime": "127 min",
	"Genre": "Adventure, Drama, Family",
	"Director": "Tim Burton",
	"imdbRating": "6.7",
	"imdbID": "tt1935859",
	"Type": "movie",
	"DateCompleted": "3/21/21"
}, {
	"Title": "The Great",
	"Year": "2020–",
	"Rated": "TV-MA",
	"Released": "15 May 2020",
	"Runtime": "45 min",
	"Genre": "Biography, Comedy, Drama",
	"Director": "N/A",
	"imdbRating": "8.2",
	"imdbID": "tt2235759",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "3/27/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Irregulars",
	"Year": "2021",
	"Rated": "TV-14",
	"Released": "26 Mar 2021",
	"Runtime": "N/A",
	"Genre": "Crime, Drama, Fantasy",
	"Director": "N/A",
	"imdbRating": "6.0",
	"imdbID": "tt10893694",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "4/6/21",
	"seasonsWatched": "1"
}, {
	"Title": "Lupin *",
	"Year": "2021–",
	"Rated": "TV-MA",
	"Released": "08 Jan 2021",
	"Runtime": "231 min",
	"Genre": "Action, Crime, Drama",
	"Director": "N/A",
	"imdbRating": "7.5",
	"imdbID": "tt2531336",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "4/6/21",
	"seasonsWatched": "1"
}, {
	"Title": "Snowpiercer *",
	"Year": "2013",
	"Rated": "R",
	"Released": "11 Jul 2014",
	"Runtime": "126 min",
	"Genre": "Action, Drama, Sci-Fi",
	"Director": "Bong Joon Ho",
	"imdbRating": "7.1",
	"imdbID": "tt1706620",
	"Type": "movie",
	"DateCompleted": "4/11/21"
}, {
	"Title": "Demon Slayer: Kimetsu no Yaiba",
	"Year": "2019–",
	"Rated": "TV-MA",
	"Released": "22 Jan 2021",
	"Runtime": "25 min",
	"Genre": "Animation, Action, Adventure",
	"Director": "N/A",
	"imdbRating": "8.7",
	"imdbID": "tt9335498",
	"Type": "series",
	"totalSeasons": "3",
	"DateCompleted": "4/11/21",
	"seasonsWatched": "1"
}, {
	"Title": "Agent Carter",
	"Year": "2015–2016",
	"Rated": "TV-PG",
	"Released": "06 Jan 2015",
	"Runtime": "42 min",
	"Genre": "Action, Adventure, Sci-Fi",
	"Director": "N/A",
	"imdbRating": "7.9",
	"imdbID": "tt3475734",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "4/15/21",
	"seasonsWatched": "1,2"
}, {
	"Title": "This Is a Robbery: The World's Greatest Art Heist",
	"Year": "2021",
	"Rated": "TV-MA",
	"Released": "07 Apr 2021",
	"Runtime": "210 min",
	"Genre": "Documentary, Crime, History",
	"Director": "N/A",
	"imdbRating": "6.5",
	"imdbID": "tt14223858",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "4/18/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Falcon and the Winter Soldier",
	"Year": "2021",
	"Rated": "TV-14",
	"Released": "19 Mar 2021",
	"Runtime": "50 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "N/A",
	"imdbRating": "7.3",
	"imdbID": "tt9208876",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "4/23/21",
	"seasonsWatched": "1"
}, {
	"Title": "Carnival Row",
	"Year": "2019–",
	"Rated": "TV-MA",
	"Released": "30 Aug 2019",
	"Runtime": "56 min",
	"Genre": "Crime, Drama, Fantasy",
	"Director": "N/A",
	"imdbRating": "7.8",
	"imdbID": "tt0489974",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "4/25/21",
	"seasonsWatched": "1"
}, {
	"Title": "Formula 1: Drive to Survive",
	"Year": "2019–",
	"Rated": "TV-MA",
	"Released": "08 Mar 2019",
	"Runtime": "40 min",
	"Genre": "Documentary, Sport",
	"Director": "N/A",
	"imdbRating": "8.6",
	"imdbID": "tt8289930",
	"Type": "series",
	"totalSeasons": "4",
	"DateCompleted": "4/28/21",
	"seasonsWatched": "1,2,3"
},{
	"Title": "Shadow and Bone",
	"Year": "2021-",
	"Rated": "TV-14",
	"Released": "23 Apr 2021",
	"Runtime": "N/A",
	"Genre": "Action, Adventure, Drama",
	"Director": "N/A",
	"imdbRating": "7.7",
	"imdbID": "tt2403776",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "5/1/21",
	"seasonsWatched": "1"
}, {
	"Title": "Stranger Than Fiction *",
	"Year": "2006",
	"Rated": "PG-13",
	"Released": "10 Nov 2006",
	"Runtime": "113 min",
	"Genre": "Comedy, Drama, Fantasy",
	"Director": "Marc Forster",
	"imdbRating": "7.5",
	"imdbID": "tt0420223",
	"Type": "movie",
	"DateCompleted": "5/2/21"
}, {
	"Title": "Made You Look",
	"Year": "2015",
	"Rated": "N/A",
	"Released": "02 Oct 2015",
	"Runtime": "70 min",
	"Genre": "Documentary",
	"Director": "Paul O'Connor Anthony Peters",
	"imdbRating": "7.7",
	"imdbID": "tt3996014",
	"Type": "movie",
	"DateCompleted": "5/4/21"
}, {
	"Title": "Thunder Force",
	"Year": "2021",
	"Rated": "PG-13",
	"Released": "09 Apr 2021",
	"Runtime": "106 min",
	"Genre": "Action, Adventure, Comedy",
	"Director": "Ben Falcone",
	"imdbRating": "4.4",
	"imdbID": "tt10121392",
	"Type": "movie",
	"DateCompleted": "5/5/21"
}, {
	"Title": "Demon Slayer: Mugen Train",
	"Year": "2020",
	"Rated": "R",
	"Released": "23 Apr 2021",
	"Runtime": "117 min",
	"Genre": "Animation, Action, Adventure",
	"Director": "Haruo Sotozaki",
	"imdbRating": "8.3",
	"imdbID": "tt11032374",
	"Type": "movie",
	"DateCompleted": "5/7/21"
}, {
	"Title": "Jupiter's Legacy",
	"Year": "2021",
	"Rated": "TV-MA",
	"Released": "07 May 2021",
	"Runtime": "N/A",
	"Genre": "Action, Adventure, Drama",
	"Director": "N/A",
	"imdbRating": "6.7",
	"imdbID": "tt5774002",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "5/8/21",
	"seasonsWatched": "1"
}, {
	"Title": "Little Miss Sumo",
	"Year": "2018",
	"Rated": "N/A",
	"Released": "28 Oct 2019",
	"Runtime": "19 min",
	"Genre": "Documentary, Short, Biography",
	"Director": "Matt Kay",
	"imdbRating": "6.6",
	"imdbID": "tt9195844",
	"Type": "movie",
	"DateCompleted": "5/15/21"
}, {
	"Title": "Ladies First",
	"Year": "2017",
	"Rated": "TV-G",
	"Released": "08 Mar 2018",
	"Runtime": "39 min",
	"Genre": "Documentary, Short, Sport",
	"Director": "Uraaz Bahl",
	"imdbRating": "7.2",
	"imdbID": "tt6896078",
	"Type": "movie",
	"DateCompleted": "5/15/21"
}, {
	"Title": "Nadiya Bakes",
	"Year": "2020–",
	"Rated": "TV-G",
	"Released": "12 Feb 2021",
	"Runtime": "29 min",
	"Genre": "Documentary",
	"Director": "N/A",
	"imdbRating": "7.1",
	"imdbID": "tt11714872",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "5/15/21",
	"seasonsWatched": "1"
}, {
	"Title": "Ramen Heads",
	"Year": "2017",
	"Rated": "Not Rated ",
	"Released": "16 Mar 2018",
	"Runtime": "93 min",
	"Genre": "Documentary",
	"Director": "Koki Shigeno",
	"imdbRating": "7.1",
	"imdbID": "tt6764122",
	"Type": "movie",
	"DateCompleted": "5/16/21"
}, {
	"Title": "Castlevania",
	"Year": "2017–2021",
	"Rated": "TV-MA",
	"Released": "07 Jul 2017",
	"Runtime": "23 min",
	"Genre": "Animation, Action, Adventure",
	"Director": "N/A",
	"imdbRating": "8.3",
	"imdbID": "tt6517102",
	"Type": "series",
	"totalSeasons": "4",
	"DateCompleted": "5/18/21",
	"seasonsWatched": "4"
}, {
	"Title": "Ottolenghi and the Cakes of Versailles",
	"Year": "2020",
	"Rated": "Not Rated ",
	"Released": "25 Sep 2020",
	"Runtime": "75 min",
	"Genre": "Documentary",
	"Director": "Laura Gabbert",
	"imdbRating": "6.1",
	"imdbID": "tt11656800",
	"Type": "movie",
	"DateCompleted": "5/21/21"
}, {
	"Title": "The Mitchells vs the Machines",
	"Year": "2021",
	"Rated": "PG",
	"Released": "30 Apr 2021",
	"Runtime": "113 min",
	"Genre": "Animation, Adventure, Comedy",
	"Director": "Michael Rianda Jeff Rowe",
	"imdbRating": "7.7",
	"imdbID": "tt7979580",
	"Type": "movie",
	"DateCompleted": "5/23/21"
}, {
	"Title": "Eurovision Song Contest: The Story of Fire Saga",
	"Year": "2020",
	"Rated": "PG-13",
	"Released": "26 Jun 2020",
	"Runtime": "123 min",
	"Genre": "Comedy, Musical",
	"Director": "David Dobkin",
	"imdbRating": "6.5",
	"imdbID": "tt8580274",
	"Type": "movie",
	"DateCompleted": "5/30/21"
}, {
	"Title": "Killing Eve",
	"Year": "2018–2022",
	"Rated": "TV-14",
	"Released": "08 Apr 2018",
	"Runtime": "42 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "N/A",
	"imdbRating": "8.2",
	"imdbID": "tt7016936",
	"Type": "series",
	"totalSeasons": "4",
	"DateCompleted": "6/4/21",
	"seasonsWatched": "1,2,3"
}, {
	"Title": "The Fifth Element *",
	"Year": "1997",
	"Rated": "PG-13",
	"Released": "09 May 1997",
	"Runtime": "126 min",
	"Genre": "Action, Adventure, Sci-Fi",
	"Director": "Luc Besson",
	"imdbRating": "7.7",
	"imdbID": "tt0119116",
	"Type": "movie",
	"DateCompleted": "6/11/21"
}, {
	"Title": "Eater's Guide to the World",
	"Year": "2020–",
	"Rated": "TV-14",
	"Released": "11 Nov 2020",
	"Runtime": "N/A",
	"Genre": "Documentary",
	"Director": "N/A",
	"imdbRating": "6.8",
	"imdbID": "tt10276462",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "6/11/21",
	"seasonsWatched": "1"
}, {
	"Title": "Lupin",
	"Year": "2021–",
	"Rated": "TV-MA",
	"Released": "08 Jan 2021",
	"Runtime": "231 min",
	"Genre": "Action, Crime, Drama",
	"Director": "N/A",
	"imdbRating": "7.5",
	"imdbID": "tt2531336",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "6/12/21",
	"seasonsWatched": "2"
}, {
	"Title": "Coded Bias",
	"Year": "2020",
	"Rated": "TV-MA",
	"Released": "11 Nov 2020",
	"Runtime": "86 min",
	"Genre": "Documentary",
	"Director": "Shalini Kantayya",
	"imdbRating": "6.7",
	"imdbID": "tt11394170",
	"Type": "movie",
	"DateCompleted": "6/17/21"
}, {
	"Title": "Inside",
	"Year": "2021",
	"Rated": "TV-MA",
	"Released": "30 May 2021",
	"Runtime": "87 min",
	"Genre": "Comedy, Drama, Music",
	"Director": "Bo Burnham",
	"imdbRating": "8.6",
	"imdbID": "tt14544192",
	"Type": "movie",
	"DateCompleted": "6/19/21"
}, {
	"Title": "Cowboy Bebop",
	"Year": "1998–1999",
	"Rated": "TV-14",
	"Released": "02 Sep 2001",
	"Runtime": "24 min",
	"Genre": "Animation, Action, Adventure",
	"Director": "N/A",
	"imdbRating": "8.9",
	"imdbID": "tt0213338",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "6/19/21"
}, {
	"Title": "Lucifer",
	"Year": "2016–2021",
	"Rated": "TV-14",
	"Released": "25 Jan 2016",
	"Runtime": "42 min",
	"Genre": "Crime, Drama, Fantasy",
	"Director": "N/A",
	"imdbRating": "8.1",
	"imdbID": "tt4052886",
	"Type": "series",
	"totalSeasons": "6",
	"DateCompleted": "6/24/21",
	"seasonsWatched": "5 part 2"
}, {
	"Title": "Space Sweepers",
	"Year": "2021",
	"Rated": "TV-MA",
	"Released": "05 Feb 2021",
	"Runtime": "136 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "Sung-hee Jo",
	"imdbRating": "6.6",
	"imdbID": "tt12838766",
	"Type": "movie",
	"DateCompleted": "7/4/21"
}, {
	"Title": "Invincible",
	"Year": "2021–",
	"Rated": "TV-MA",
	"Released": "26 Mar 2021",
	"Runtime": "N/A",
	"Genre": "Animation, Action, Adventure",
	"Director": "N/A",
	"imdbRating": "8.7",
	"imdbID": "tt6741278",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "7/23/21",
	"seasonsWatched": "1"
}, {
	"Title": "Golden: The Journey of USA's Elite Gymnasts",
	"Year": "2021–",
	"Rated": "N/A",
	"Released": "27 Jun 2021",
	"Runtime": "N/A",
	"Genre": "Documentary, Sport",
	"Director": "N/A",
	"imdbRating": "8.9",
	"imdbID": "tt14536364",
	"Type": "series",
	"totalSeasons": "N/A",
	"DateCompleted": "7/26/21",
	"seasonsWatched": "1"
}, {
	"Title": "Ghost in the Shell",
	"Year": "1995",
	"Rated": "TV-MA",
	"Released": "29 Mar 1996",
	"Runtime": "83 min",
	"Genre": "Animation, Action, Crime",
	"Director": "Mamoru Oshii",
	"imdbRating": "8.0",
	"imdbID": "tt0113568",
	"Type": "movie",
	"DateCompleted": "7/31/21"
}, {
	"Title": "The Suicide Squad",
	"Year": "2021",
	"Rated": "R",
	"Released": "05 Aug 2021",
	"Runtime": "132 min",
	"Genre": "Action, Adventure, Comedy",
	"Director": "James Gunn",
	"imdbRating": "7.2",
	"imdbID": "tt6334354",
	"Type": "movie",
	"DateCompleted": "8/6/21"
}, {
	"Title": "The Man in the High Castle",
	"Year": "2015–2019",
	"Rated": "TV-MA",
	"Released": "15 Jan 2015",
	"Runtime": "60 min",
	"Genre": "Drama, Sci-Fi, Thriller",
	"Director": "N/A",
	"imdbRating": "8.0",
	"imdbID": "tt1740299",
	"Type": "series",
	"totalSeasons": "4",
	"DateCompleted": "8/8/21",
	"seasonsWatched": "4"
}, {
	"Title": "Making the Cut",
	"Year": "2020–",
	"Rated": "TV-14",
	"Released": "27 Mar 2020",
	"Runtime": "60 min",
	"Genre": "Game-Show, Reality-TV",
	"Director": "N/A",
	"imdbRating": "6.6",
	"imdbID": "tt8962394",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "8/12/21",
	"seasonsWatched": "1,2"
}, {
	"Title": "Blade Runner 2049",
	"Year": "2017",
	"Rated": "R",
	"Released": "06 Oct 2017",
	"Runtime": "164 min",
	"Genre": "Action, Drama, Mystery",
	"Director": "Denis Villeneuve",
	"imdbRating": "8.0",
	"imdbID": "tt1856101",
	"Type": "movie",
	"DateCompleted": "8/13/21"
}, {
	"Title": "Devs",
	"Year": "2020",
	"Rated": "TV-MA",
	"Released": "05 Mar 2020",
	"Runtime": "409 min",
	"Genre": "Drama, Mystery, Sci-Fi",
	"Director": "N/A",
	"imdbRating": "7.7",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "8/17/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Secret Life of Walter Mitty",
	"Year": "2013",
	"Rated": "PG",
	"Released": "25 Dec 2013",
	"Runtime": "114 min",
	"Genre": "Adventure, Comedy, Drama",
	"Director": "Ben Stiller",
	"imdbRating": "7.3",
	"imdbID": "tt0359950",
	"Type": "movie",
	"DateCompleted": "8/20/21"
}, {
	"Title": "Black Widow",
	"Year": "2021",
	"Rated": "PG-13",
	"Released": "09 Jul 2021",
	"Runtime": "134 min",
	"Genre": "Action, Adventure, Sci-Fi",
	"Director": "Cate Shortland",
	"imdbRating": "6.7",
	"imdbID": "tt3480822",
	"Type": "movie",
	"DateCompleted": "8/22/21"
}, {
	"Title": "Motherland: Fort Salem",
	"Year": "2020–2022",
	"Rated": "TV-14",
	"Released": "18 Mar 2020",
	"Runtime": "N/A",
	"Genre": "Drama, Fantasy, Sci-Fi",
	"Director": "N/A",
	"imdbRating": "7.3",
	"imdbID": "tt9900092",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "8/26/21",
	"seasonsWatched": "1,2"
}, {
	"Title": "The Witcher: Nightmare of the Wolf",
	"Year": "2021",
	"Rated": "TV-MA",
	"Released": "23 Aug 2021",
	"Runtime": "83 min",
	"Genre": "Animation, Action, Adventure",
	"Director": "Kwang Il Han",
	"imdbRating": "7.3",
	"imdbID": "tt11657662",
	"Type": "movie",
	"DateCompleted": "8/29/21"
}, {
	"Title": "Loki",
	"Year": "2021–",
	"Rated": "TV-14",
	"Released": "09 Jun 2021",
	"Runtime": "N/A",
	"Genre": "Action, Adventure, Fantasy",
	"Director": "N/A",
	"imdbRating": "8.3",
	"imdbID": "tt9140554",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "9/2/21",
	"seasonsWatched": "1"
}, {
	"Title": "Superfast! *",
	"Year": "2015",
	"Rated": "PG-13",
	"Released": "03 Apr 2015",
	"Runtime": "99 min",
	"Genre": "Comedy",
	"Director": "Jason Friedberg Aaron Seltzer",
	"imdbRating": "4.1",
	"imdbID": "tt2933474",
	"Type": "movie",
	"DateCompleted": "9/4/21"
}, {
	"Title": "Beowulf *",
	"Year": "2007",
	"Rated": "PG-13",
	"Released": "16 Nov 2007",
	"Runtime": "115 min",
	"Genre": "Animation, Action, Adventure",
	"Director": "Robert Zemeckis",
	"imdbRating": "6.2",
	"imdbID": "tt0442933",
	"Type": "movie",
	"DateCompleted": "9/11/21"
}, {
	"Title": "Captain America: The First Avenger *",
	"Year": "2011",
	"Rated": "PG-13",
	"Released": "22 Jul 2011",
	"Runtime": "124 min",
	"Genre": "Action, Adventure, Sci-Fi",
	"Director": "Joe Johnston",
	"imdbRating": "6.9",
	"imdbID": "tt0458339",
	"Type": "movie",
	"DateCompleted": "9/10/21"
}, {
	"Title": "Captain America: The Winter Soldier *",
	"Year": "2014",
	"Rated": "PG-13",
	"Released": "04 Apr 2014",
	"Runtime": "136 min",
	"Genre": "Action, Adventure, Sci-Fi",
	"Director": "Anthony Russo Joe Russo",
	"imdbRating": "7.7",
	"imdbID": "tt1843866",
	"Type": "movie",
	"DateCompleted": "9/12/21"
}, {
	"Title": "Thor *",
	"Year": "2011",
	"Rated": "PG-13",
	"Released": "06 May 2011",
	"Runtime": "115 min",
	"Genre": "Action, Adventure, Fantasy",
	"Director": "Kenneth Branagh",
	"imdbRating": "7.0",
	"imdbID": "tt0800369",
	"Type": "movie",
	"DateCompleted": "9/17/21"
}, {
	"Title": "The Avengers *",
	"Year": "2012",
	"Rated": "PG-13",
	"Released": "04 May 2012",
	"Runtime": "143 min",
	"Genre": "Action, Adventure, Sci-Fi",
	"Director": "Joss Whedon",
	"imdbRating": "8.0",
	"imdbID": "tt0848228",
	"Type": "movie",
	"DVD": "25 Sep 2012",
	"DateCompleted": "9/17/21"
}, {
	"Title": "Doctor Strange *",
	"Year": "2016",
	"Rated": "PG-13",
	"Released": "04 Nov 2016",
	"Runtime": "115 min",
	"Genre": "Action, Adventure, Fantasy",
	"Director": "Scott Derrickson",
	"imdbRating": "7.5",
	"imdbID": "tt1211837",
	"Type": "movie",
	"DateCompleted": "9/19/21"
}, {
	"Title": "Guardians of the Galaxy *",
	"Year": "2014",
	"Rated": "PG-13",
	"Released": "01 Aug 2014",
	"Runtime": "121 min",
	"Genre": "Action, Adventure, Comedy",
	"Director": "James Gunn",
	"imdbRating": "8.0",
	"imdbID": "tt2015381",
	"Type": "movie",
	"DateCompleted": "9/19/21"
}, {
	"Title": "Captain America: Civil War *",
	"Year": "2016",
	"Rated": "PG-13",
	"Released": "06 May 2016",
	"Runtime": "147 min",
	"Genre": "Action, Adventure, Sci-Fi",
	"Director": "Anthony Russo Joe Russo",
	"imdbRating": "7.8",
	"imdbID": "tt3498820",
	"Type": "movie",
	"DateCompleted": "9/25/21"
}, {
	"Title": "What We Do in the Shadows *",
	"Year": "2014",
	"Rated": "R",
	"Released": "13 Feb 2015",
	"Runtime": "86 min",
	"Genre": "Comedy, Horror",
	"Director": "Jemaine Clement Taika Waititi",
	"imdbRating": "7.7",
	"imdbID": "tt3416742",
	"Type": "movie",
	"DateCompleted": "9/25/21"
}, {
	"Title": "Star Wars: Visions",
	"Year": "2021–",
	"Rated": "TV-PG",
	"Released": "22 Sep 2021",
	"Runtime": "N/A",
	"Genre": "Animation, Action, Adventure",
	"Director": "N/A",
	"imdbRating": "7.1",
	"imdbID": "tt13622982",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "9/25/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Haunting of Hill House",
	"Year": "2018",
	"Rated": "TV-MA",
	"Released": "12 Oct 2018",
	"Runtime": "572 min",
	"Genre": "Drama, Horror, Mystery",
	"Director": "Mike Flanagan",
	"imdbRating": "8.6",
	"imdbID": "tt6763664",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "10/2/21"
}, {
	"Title": "Lucifer",
	"Year": "2016–2021",
	"Rated": "TV-14",
	"Released": "25 Jan 2016",
	"Runtime": "42 min",
	"Genre": "Crime, Drama, Fantasy",
	"Director": "N/A",
	"imdbRating": "8.1",
	"imdbID": "tt4052886",
	"Type": "series",
	"totalSeasons": "6",
	"DateCompleted": "10/3/21",
	"seasonsWatched": "6"
}, {
	"Title": "Cruella",
	"Year": "2021",
	"Rated": "PG-13",
	"Released": "28 May 2021",
	"Runtime": "134 min",
	"Genre": "Adventure, Comedy, Crime",
	"Director": "Craig Gillespie",
	"imdbRating": "7.4",
	"imdbID": "tt3228774",
	"Type": "movie",
	"DateCompleted": "10/6/21"
}, {
	"Title": "What If...?",
	"Year": "2021–",
	"Rated": "TV-14",
	"Released": "11 Aug 2021",
	"Runtime": "N/A",
	"Genre": "Animation, Action, Adventure",
	"Director": "N/A",
	"imdbRating": "7.5",
	"imdbID": "tt10168312",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "10/7/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Defeated",
	"Year": "2020–",
	"Rated": "TV-MA",
	"Released": "30 Oct 2020",
	"Runtime": "45 min",
	"Genre": "Drama, Thriller",
	"Director": "N/A",
	"imdbRating": "7.1",
	"imdbID": "tt8879894",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "10/9/21",
	"seasonsWatched": "1"
}, {
	"Title": "Radium Girls",
	"Year": "2018",
	"Rated": "Not Rated ",
	"Released": "15 Dec 2020",
	"Runtime": "102 min",
	"Genre": "Drama, History",
	"Director": "Lydia Dean Pilcher Ginny Mohler",
	"imdbRating": "6.3",
	"imdbID": "tt6317180",
	"Type": "movie",
	"DateCompleted": "10/10/21"
}, {
	"Title": "Thor: Ragnarok *",
	"Year": "2017",
	"Rated": "PG-13",
	"Released": "03 Nov 2017",
	"Runtime": "130 min",
	"Genre": "Action, Adventure, Comedy",
	"Director": "Taika Waititi",
	"imdbRating": "7.9",
	"imdbID": "tt3501632",
	"Type": "movie",
	"DateCompleted": "10/13/21"
}, {
	"Title": "Dune",
	"Year": "2021",
	"Rated": "PG-13",
	"Released": "22 Oct 2021",
	"Runtime": "155 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "Denis Villeneuve",
	"imdbRating": "8.1",
	"imdbID": "tt1160419",
	"Type": "movie",
	"DateCompleted": "10/22/21"
}, {
	"Title": "Halloweentown *",
	"Year": "1998",
	"Rated": "TV-G",
	"Released": "17 Oct 1998",
	"Runtime": "84 min",
	"Genre": "Adventure, Comedy, Family, Fantasy",
	"Director": "Duwayne Dunham",
	"imdbRating": "6.7",
	"imdbID": "tt0173886",
	"Type": "movie",
	"DateCompleted": "10/23/21"
}, {
	"Title": "The Haunting of Bly Manor",
	"Year": "2020",
	"Rated": "TV-MA",
	"Released": "09 Oct 2020",
	"Runtime": "494 min",
	"Genre": "Drama, Horror, Mystery",
	"Director": "Mike Flanagan",
	"imdbRating": "7.4",
	"imdbID": "tt10970552",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "10/24/21",
	"seasonsWatched": "1"
}, {
	"Title": "Midnight Mass",
	"Year": "2021",
	"Rated": "TV-MA",
	"Released": "24 Sep 2021",
	"Runtime": "40 min",
	"Genre": "Drama, Fantasy, Horror",
	"Director": "Mike Flanagan",
	"imdbRating": "7.7",
	"imdbID": "tt10574558",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "10/28/21",
	"seasonsWatched": "1"
}, {
	"Title": "Hocus Pocus *",
	"Year": "1993",
	"Rated": "PG",
	"Released": "16 Jul 1993",
	"Runtime": "96 min",
	"Genre": "Comedy, Family, Fantasy",
	"Director": "Kenny Ortega",
	"imdbRating": "6.9",
	"imdbID": "tt0107120",
	"Type": "movie",
	"DateCompleted": "10/31/21"
}, {
	"Title": "What We Do in the Shadows",
	"Year": "2019–",
	"Rated": "TV-MA",
	"Released ": "27 Mar 2019",
	"Runtime ": "30 min",
	"Genre": "Comedy, Fantasy, Horror",
	"Director ": "Jemaine Clement, Taika Waititi",
	"imdbRating ": "8.6",
	"imdbID ": "tt7908628",
	"Type ": "series",
	"totalSeasons ": "4",
	"DateCompleted": "10/31/21",
	"seasonsWatched": "3"
}, {
	"Title": "Holes *",
	"Year": "2003",
	"Rated": "PG",
	"Released": "18 Apr 2003",
	"Runtime": "117 min",
	"Genre": "Adventure, Comedy, Drama",
	"Director": "Andrew Davis",
	"imdbRating": "7.0",
	"imdbID": "tt0311289",
	"Type": "movie",
	"DateCompleted": "11/6/21"
}, {
	"Title": "Call the Midwife",
	"Year": "2012–",
	"Rated": "TV-PG",
	"Released": "15 Jan 2012",
	"Runtime": "60 min",
	"Genre": "Drama, History",
	"Director": "N/A",
	"imdbRating": "8.5",
	"imdbID": "tt1983079",
	"Type": "series",
	"totalSeasons": "11",
	"DateCompleted": "11/7/21",
	"seasonsWatched": "1,2,3,4,5,6,7,8,9"
}, {
	"Title": "Layer Cake",
	"Year": "2004",
	"Rated": "R",
	"Released": "03 Jun 2005",
	"Runtime": "105 min",
	"Genre": "Action, Crime, Drama",
	"Director": "Matthew Vaughn",
	"imdbRating": "7.3",
	"imdbID": "tt0375912",
	"Type": "movie",
	"DateCompleted": "11/11/21"
}, {
	"Title": "Shang-Chi and the Legend of the Ten Rings",
	"Year": "2021",
	"Rated": "PG-13",
	"Released": "03 Sep 2021",
	"Runtime": "132 min",
	"Genre": "Action, Adventure, Fantasy",
	"Director": "Destin Daniel Cretton",
	"imdbRating": "7.5",
	"imdbID": "tt9376612",
	"Type": "movie",
	"DateCompleted": "11/13/21"
}, {
	"Title": "Eternals",
	"Year": "2021",
	"Rated": "PG-13",
	"Released": "05 Nov 2021",
	"Runtime": "156 min",
	"Genre": "Action, Adventure, Fantasy",
	"Director": "Chloé Zhao",
	"imdbRating": "6.4",
	"imdbID": "tt9032400",
	"Type": "movie",
	"DateCompleted": "11/13/21"
}, {
	"Title": "Yellowstone",
	"Year": "2018–",
	"Rated": "TV-MA",
	"Released": "20 Jun 2018",
	"Runtime": "60 min",
	"Genre": "Drama, Western",
	"Director": "N/A",
	"imdbRating": "8.8",
	"imdbID": "tt4236770",
	"Type": "series",
	"totalSeasons": "5",
	"DateCompleted": "11/11/21",
	"seasonsWatched": "1,2,3"
}, {
	"Title": "Cowboy Bebop",
	"Year": "2021",
	"Rated": "TV-MA",
	"Released": "19 Nov 2021",
	"Runtime": "N/A",
	"Genre": "Action, Adventure, Comedy",
	"Director": "N/A",
	"imdbRating": "6.6",
	"imdbID": "tt1267295",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "11/20/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Great British Baking Show",
	"Year": "2010–",
	"Rated": "TV-PG",
	"Released": "27 Dec 2014",
	"Runtime": "60 min",
	"Genre": "Reality-TV",
	"Director": "N/A",
	"imdbRating": "8.6",
	"imdbID": "tt1877368",
	"Type": "series",
	"totalSeasons": "12",
	"DateCompleted": "11/26/21",
	"seasonsWatched": "9"
}, {
	"Title": "Reservation Dogs",
	"Year": "2021–",
	"Rated": "TV-MA",
	"Released": "09 Aug 2021",
	"Runtime": "N/A",
	"Genre": "Comedy, Crime",
	"Director": "N/A",
	"imdbRating": "8.1",
	"imdbID": "tt13623580",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "12/4/21",
	"seasonsWatched": "1"
}, {
	"Title": "Arcane",
	"Year": "2021–",
	"Rated": "TV-14",
	"Released": "06 Nov 2021",
	"Runtime": "N/A",
	"Genre": "Animation, Action, Adventure",
	"Director": "N/A",
	"imdbRating": "9.1",
	"imdbID": "tt11126994",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "12/8/21",
	"seasonsWatched": "1"
}, {
	"Title": "The Harder They Fall",
	"Year": "2021",
	"Rated": "R",
	"Released": "03 Nov 2021",
	"Runtime": "139 min",
	"Genre": "Action, Drama, Western",
	"Director": "Jeymes Samuel",
	"imdbRating": "6.6",
	"imdbID": "tt10696784",
	"Type": "movie",
	"DateCompleted": "12/10/21"
}, {
	"Title": "The Matrix *",
	"Year": "1999",
	"Rated": "R",
	"Released": "31 Mar 1999",
	"Runtime": "136 min",
	"Genre": "Action, Sci-Fi",
	"Director": "Lana Wachowski Lilly Wachowski",
	"imdbRating": "8.7",
	"imdbID": "tt0133093",
	"Type": "movie",
	"DateCompleted": "12/11/21"
}, {
	"Title": "The Witcher",
	"Year": "2019–",
	"Rated": "TV-MA",
	"Released": "20 Dec 2019",
	"Runtime": "60 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "Tomek Baginski",
	"imdbRating": "8.2",
	"imdbID": "tt5180504",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "12/18/21",
	"seasonsWatched": "2"
}, {
	"Title": "Hawkeye",
	"Year": "2021",
	"Rated": "TV-14",
	"Released": "24 Nov 2021",
	"Runtime": "60 min",
	"Genre": "Action, Adventure, Crime",
	"Director": "N/A",
	"imdbRating": "7.7",
	"imdbID": "tt10160804",
	"Type": "series",
	"totalSeasons": "1",
	"DateCompleted": "12/22/21",
	"seasonsWatched": "1"
}, {
	"Title": "A Merry Friggin' Christmas",
	"Year": "2014",
	"Rated": "PG-13",
	"Released": "22 Nov 2014",
	"Runtime": "88 min",
	"Genre": "Comedy, Drama",
	"Director": "Tristram Shapeero",
	"imdbRating": "5.2",
	"imdbID": "tt0910885",
	"Type": "movie",
	"DateCompleted": "12/22/21"
}, {
	"Title": "Belfast",
	"Year": "2021",
	"Rated": "PG-13",
	"Released": "12 Nov 2021",
	"Runtime": "98 min",
	"Genre": "Biography, Drama, History",
	"Director": "Kenneth Branagh",
	"imdbRating": "7.3",
	"imdbID": "tt12789558",
	"Type": "movie",
	"DateCompleted": "12/23/21"
}, {
	"Title": "The Power of the Dog",
	"Year": "2021",
	"Rated": "R",
	"Released": "01 Dec 2021",
	"Runtime": "126 min",
	"Genre": "Drama, Romance, Western",
	"Director": "Jane Campion",
	"imdbRating": "6.9",
	"imdbID": "tt10293406",
	"Type": "movie",
	"DateCompleted": "12/27/21"
}, {
	"Title": "Encanto",
	"Year": "2021",
	"Rated": "PG",
	"Released": "24 Nov 2021",
	"Runtime": "102 min",
	"Genre": "Animation, Comedy, Family",
	"Director": "Jared Bush Byron Howard Charise Castro Smith",
	"imdbRating": "7.3",
	"imdbID": "tt2953050",
	"Type": "movie",
	"DateCompleted": "12/28/21"
}, {
	"Title": "Letterkenny",
	"Year": "2016–",
	"Rated": "TV-MA",
	"Released": "07 Feb 2016",
	"Runtime": "30 min",
	"Genre": "Comedy",
	"Director": "N/A",
	"imdbRating": "8.6",
	"imdbID": "tt4647692",
	"Type": "series",
	"totalSeasons": "10",
	"DateCompleted": "12/29/21",
	"seasonsWatched": "10"
}, {
	"Title": "Luca",
	"Year": "2021",
	"Rated": "PG",
	"Released": "18 Jun 2021",
	"Runtime": "95 min",
	"Genre": "Animation, Adventure, Comedy",
	"Director": "Enrico Casarosa",
	"imdbRating": "7.5",
	"imdbID": "tt12801262",
	"Type": "movie",
	"DateCompleted": "12/29/21"
}, {
	"Title": "Coco",
	"Year": "2017",
	"Rated": "PG",
	"Released": "22 Nov 2017",
	"Runtime": "105 min",
	"Genre": "Animation, Adventure, Comedy",
	"Director": "Lee Unkrich Adrian Molina",
	"imdbRating": "8.4",
	"imdbID": "tt2380307",
	"Type": "movie",
	"DateCompleted": "12/30/21"
}, {
	"Title": "The Great",
	"Year": "2020–",
	"Rated": "TV-MA",
	"Released": "15 May 2020",
	"Runtime": "45 min",
	"Genre": "Biography, Comedy, Drama",
	"Director": "N/A",
	"imdbRating": "8.2",
	"imdbID": "tt2235759",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "1/13/22",
	"seasonsWatched": "2"
}, {
	"Title": "The Expanse",
	"Year": "2015–",
	"Rated": "TV-14",
	"Released": "23 Nov 2015",
	"Runtime": "60 min",
	"Genre": "Drama, Mystery, Sci-Fi",
	"Director": "N/A",
	"imdbRating": "8.5",
	"imdbID": "tt3230854",
	"Type": "series",
	"totalSeasons": "6",
	"DateCompleted": "1/21/22",
	"seasonsWatched": "6"
}, {
	"Title": "The Wheel of Time",
	"Year": "2021–",
	"Rated": "TV-14",
	"Released": "19 Nov 2021",
	"Runtime": "60 min",
	"Genre": "Action, Adventure, Drama",
	"Director": "N/A",
	"imdbRating": "7.2",
	"imdbID": "tt7462410",
	"Type": "series",
	"totalSeasons": "2",
	"DateCompleted": "1/25/22",
	"seasonsWatched": "1"
}, {
	"Title": "Ozark",
	"Year": "2017–2022",
	"Rated": "TV-MA",
	"Released": "21 Jul 2017",
	"Runtime": "60 min",
	"Genre": "Crime, Drama, Thriller",
	"Director": "N/A",
	"imdbRating": "8.5",
	"imdbID": "tt5071412",
	"Type": "series",
	"totalSeasons": "4",
	"DateCompleted": "2/7/22",
	"seasonsWatched": "4 part 1"
}]

export default watchlistData;